########################################################################
#
# Copyright (C) 2024
# Associated Universities, Inc. Washington DC, USA.
#
# This script is free software; you can redistribute it and/or modify it
# under the terms of the GNU Library General Public License as published by
# the Free Software Foundation; either version 2 of the License, or (at your
# option) any later version.
#
# This library is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
# FITNESS FOR A PARTICULAR PURPOSE.  See the GNU Library General Public
# License for more details.
#
# You should have received a copy of the GNU Library General Public License
# along with this library; if not, write to the Free Software Foundation,
# Inc., 675 Massachusetts Ave, Cambridge, MA 02139, USA.
#
# Correspondence concerning AIPS++ should be adressed as follows:
#        Internet email: casa-feedback@nrao.edu.
#        Postal address: AIPS++ Project Office
#                        National Radio Astronomy Observatory
#                        520 Edgemont Road
#                        Charlottesville, VA 22903-2475 USA
#
########################################################################
##################### generated by sync_layers from VisibilityPlotter
from __future__ import absolute_import
from typing import Optional
from casashell.private.stack_manip import find_local as __sf__
from casashell.private.stack_manip import find_frame as _find_frame
from casatasks.private.task_logging import start_log as _start_log
from casatasks.private.task_logging import end_log as _end_log
from casatasks.private.task_logging import except_log as _except_log
from cubevis.toolbox.visplot.visibility_plotter import VisibilityPlotter
from collections import OrderedDict
import sys
import os
import shutil


def static_var(varname, value):
    def decorate(func):
        setattr(func, varname, value)
        return func
    return decorate


# Sentinel that distinguishes "caller passed nothing" from "caller passed None".
# Required because several parameters have None as their legitimate default
# value, so `x is None` cannot serve as the "unset" test in __call__.
_UNSET = object()


def _visplot_t(
        *,
        ms: Optional[str] = None,
        ps: Optional[str] = None,
        backend: str = 'auto',
        field: str = '',
        spw: str = '',
        antenna: str = '',
        scan: str = '',
        timerange: str = '',
        uvrange: str = '',
        correlation: str = '',
        datacolumn: str = 'data',
        layout: str = 'side',
        preset: Optional[str] = None,
        raster_y: Optional[str] = None,
        raster_x: Optional[str] = None,
        raster_qty: Optional[str] = None,
        scatter_x: Optional[str] = None,
        scatter_y: Optional[str] = None,
        time_range: tuple[float, float] | list[float] | None = None,
        freq_range: tuple[float, float] | list[float] | None = None,
        uvdist_range: tuple[float, float] | list[float] | None = None,
        compact_toolbar: bool = True,
):
    _app = VisibilityPlotter(
        # user-supplied arguments
        ms = ms,
        ps = ps,
        backend = backend,
        field = field,
        spw = spw,
        antenna = antenna,
        scan = scan,
        timerange = timerange,
        uvrange = uvrange,
        correlation = correlation,
        datacolumn = datacolumn,
        layout = layout,
        preset = preset,
        raster_y = raster_y,
        raster_x = raster_x,
        raster_qty = raster_qty,
        scatter_x = scatter_x,
        scatter_y = scatter_y,
        time_range = time_range,
        freq_range = freq_range,
        uvdist_range = uvdist_range,
        compact_toolbar = compact_toolbar,
        # layer-supplied arguments
        remote_endpoint = None,
        enable_flagging = True,
    )
    return _app()


class _visplot:
    r"""
    Combined raster + scatter visibility inspection and flagging tool.

    Parameters
    ----------
    ms : str | None
        Path to an MSv2 measurement set.  Exactly one of ``ms`` or ``ps``
        must be supplied.
    ps : str | None
        Path to an MSv4 / Processing Set Zarr store.
    backend : str
        Reduction backend: ``"auto"``, ``"casa6"``, ``"radps"``,
        ``"remote"``, or ``"null"``.  Default ``"auto"``.
    remote_endpoint : str | None
        Required only when ``backend="remote"``.
    field : str
        Field name or integer index string.  Default: first field.
    spw : str
        Comma-separated SPW indices (``"0,1,2,3"``).  Default: all.
    antenna : str
        MSSelection antenna string.  (Stored; not yet wired in preview.)
    scan : str
        MSSelection scan string.  (Stored; not yet wired.)
    timerange : str
        MSSelection time-range string.  (Stored; not wired.)
    uvrange : str
        UV range string.  (Stored; not wired.)
    correlation : str
        Comma-separated correlation labels (``"XX,YY"``).  Default: all.
    datacolumn : str
        Visibility column: ``"data"``, ``"corrected"``, or ``"model"``.
    layout : str
        Panel layout: ``"one"`` (single panel, raster by default in this
        preview — per-panel kind switching is a later addition),
        ``"side"`` (both panels, side by side), or ``"over"`` (both
        panels, one above the other). Default ``"side"``.
    preset : str | None
        Named preset: ``"vplot"``, ``"radplot"``, ``"waterfall"``, or ``None``.
    raster_y, raster_x : str | None
        Explicit raster Y/X axis, e.g. ``"TIME"``, ``"BASELINE"``,
        ``"CHANNEL"``, ``"CORRELATION"``. Takes precedence over
        ``preset``, which takes precedence over the default
        (Time vs. Channel). Validated against the same options the
        raster axis dropdowns expose in the GUI — an invalid value
        raises ``ValueError`` listing the valid options.
    raster_qty : str | None
        Explicit raster quantity (color axis), e.g. ``"AMPLITUDE"``,
        ``"PHASE"``, ``"REAL"``, ``"IMAGINARY"``, ``"FLAG"``. Same
        precedence and validation as ``raster_y``/``raster_x``.
    scatter_x, scatter_y : str | None
        Explicit scatter X/Y axis, e.g. ``"UVDIST"``, ``"TIME"``,
        ``"FREQUENCY"``, ``"CHANNEL"``, ``"UVDIST_LAMBDA"``, ``"U"``,
        ``"V"`` for X; ``"AMPLITUDE"``, ``"PHASE"``, ``"REAL"``,
        ``"IMAGINARY"``, ``"U"``, ``"V"`` for Y. Same precedence and
        validation. E.g. ``scatter_x="U", scatter_y="V"`` launches
        directly into a U-vs-V UV-coverage scatter plot with no manual
        axis-picker step needed.
    time_range : tuple[float, float] | list[float] | None
        ``(start, end)`` as MJD floats.
    freq_range : tuple[float, float] | list[float] | None
        ``(start, end)`` in Hz.
    uvdist_range : tuple[float, float] | list[float] | None
        ``(min, max)`` in metres.
    compact_toolbar : bool
        Whether each figure's toolbar auto-hides until the mouse is over
        that plot.  Defaults to ``True``.
    """

    _info_group_ = """visualization, information,editing, manipulation"""
    _info_desc_  = """A plotter/interactive flagger for visibility data"""

    # Per-parameter short descriptions, used by inp() display.
    _arg_description = {
        'ms': 'Path to an MSv2 measurement set.',
        'ps': 'Path to an MSv4 / Processing Set Zarr store.',
        'backend': 'Reduction backend: ``"auto"``, ``"casa6"``, ``"radps"``, ``"remote"``, or ``"null"``.',
        'field': 'Field name or integer index string.',
        'spw': 'Comma-separated SPW indices (``"0,1,2,3"``).',
        'antenna': 'MSSelection antenna string.',
        'scan': 'MSSelection scan string.',
        'timerange': 'MSSelection time-range string.',
        'uvrange': 'UV range string.',
        'correlation': 'Comma-separated correlation labels (``"XX,YY"``).',
        'datacolumn': 'Visibility column: ``"data"``, ``"corrected"``, or ``"model"``.',
        'layout': 'Panel layout: ``"one"`` (single panel, raster by default in this preview — per-panel kind switching is a later addition), ``"side"`` (both panels, side by side), or ``"over"`` (both panels, one above the other).',
        'preset': 'Named startup preset (vplot, radplot, waterfall).',
        'raster_y': '',
        'raster_x': '',
        'raster_qty': 'Explicit raster quantity (color axis), e.g.',
        'scatter_x': '',
        'scatter_y': '',
        'time_range': '``(start, end)`` as MJD floats.',
        'freq_range': '``(start, end)`` in Hz.',
        'uvdist_range': '``(min, max)`` in metres.',
        'compact_toolbar': 'Whether each figure's toolbar auto-hides until the mouse is over that plot.',
    }

    # Default values, derived from the canonical interface signature.
    _arg_default = {
        'ms': None,
        'ps': None,
        'backend': 'auto',
        'field': '',
        'spw': '',
        'antenna': '',
        'scan': '',
        'timerange': '',
        'uvrange': '',
        'correlation': '',
        'datacolumn': 'data',
        'layout': 'side',
        'preset': None,
        'raster_y': None,
        'raster_x': None,
        'raster_qty': None,
        'scatter_x': None,
        'scatter_y': None,
        'time_range': None,
        'freq_range': None,
        'uvdist_range': None,
        'compact_toolbar': True,
    }

    def __init__(self):
        self.__stdout      = None
        self.__stderr      = None
        self.__root_frame_ = None

    def __globals_(self):
        if self.__root_frame_ is None:
            self.__root_frame_ = _find_frame()
            assert self.__root_frame_ is not None, \
                "could not find CASAshell global frame"
        return self.__root_frame_

    def __to_string_(self, value):
        if type(value) is str:
            return "'%s'" % value
        else:
            return str(value)

    def __validate_(self, name, value):
        """Lightweight type-annotation-based validator.

        Returns True when *value* is consistent with the type annotation
        of parameter *name* in ``VisibilityPlotter.__init__``.  Used by
        ``inp()`` to drive colorization (blue = changed from default,
        red = invalid, no color = at default).

        The check is intentionally permissive: it accepts ``None`` for any
        ``Optional[...]`` parameter and otherwise does a simple
        ``isinstance`` check on the base type.  Complex union types fall
        back to ``True`` so that a valid value is never falsely rejected.

        Where ``validator_overrides`` were specified in ``project_layers.yaml``,
        the overriding type expression is used instead of the annotation.
        """
        # Type map: annotation string (or override) per parameter name.
        # Override entries are set explicitly via validator_overrides in YAML.
        _type_map = {
            'ms': 'Optional[str]',
            'ps': 'Optional[str]',
            'backend': 'str',
            'field': 'str',
            'spw': 'str',
            'antenna': 'str',
            'scan': 'str',
            'timerange': 'str',
            'uvrange': 'str',
            'correlation': 'str',
            'datacolumn': 'str',
            'layout': 'str',
            'preset': 'Optional[str]',
            'raster_y': 'Optional[str]',
            'raster_x': 'Optional[str]',
            'raster_qty': 'Optional[str]',
            'scatter_x': 'Optional[str]',
            'scatter_y': 'Optional[str]',
            'time_range': 'tuple[float, float] | list[float] | None',
            'freq_range': 'tuple[float, float] | list[float] | None',
            'uvdist_range': 'tuple[float, float] | list[float] | None',
            'compact_toolbar': 'bool',
        }
        ann = _type_map.get(name, '')
        if not ann:
            return True
        import re as _re
        # Normalise both Optional[X] and "X | None" / "None | X" to just X,
        # accepting None for either form.
        m = _re.match(r'Optional\[(.+)\]', ann)
        if m:
            if value is None:
                return True
            ann = m.group(1)
        elif '|' in ann:
            parts = [p.strip() for p in ann.split('|')]
            if 'None' in parts:
                if value is None:
                    return True
                parts = [p for p in parts if p != 'None']
            # Flatten remaining union — accept if value matches any branch.
            # Parameterised generics like tuple[float, float] are reduced to
            # their base type (tuple) for the isinstance check.
            ann = '|'.join(parts)
        # Map annotation strings to Python types.  Parameterised generics
        # (e.g. "tuple[float, float]") are matched by their base name.
        # Parenthesised override expressions (e.g. "(tuple, list)") are also
        # handled here so validator_overrides still work.
        _simple = {
            'str': str, 'int': int, 'float': float,
            'bool': bool, 'tuple': tuple, 'list': list,
        }
        if ann.startswith('(') and ann.endswith(')'):
            py_types = tuple(
                _simple[t.strip()]
                for t in ann[1:-1].split(',')
                if t.strip() in _simple
            )
            return isinstance(value, py_types) if py_types else True
        if '|' in ann:
            # Remaining union after None-stripping: accept if any branch matches
            py_types = tuple(
                _simple[_re.match(r'(\w+)', b.strip()).group(1)]
                for b in ann.split('|')
                if _re.match(r'(\w+)', b.strip()) and
                   _re.match(r'(\w+)', b.strip()).group(1) in _simple
            )
            return isinstance(value, py_types) if py_types else True
        # Single type — strip any parameterisation, e.g. tuple[float, float] → tuple
        base = _re.match(r'(\w+)', ann)
        if base:
            py_type = _simple.get(base.group(1))
            if py_type is not None:
                return isinstance(value, py_type)
        # Unknown / complex type — accept
        return True

    def __do_inp_output(self, param_prefix, description_str, formatting_chars):
        out = self.__stdout or sys.stdout
        description = description_str.split()
        prefix_width = 23 + 23 + 4
        output = []
        addon = ''
        first_addon = True
        if len(description) == 0:
            out.write(param_prefix + " #\n")
            return
        while len(description) > 0:
            if len(output) == 0:
                if len(param_prefix) - formatting_chars > prefix_width - 1:
                    output.append(param_prefix)
                    continue
                addon = param_prefix + ' #'
                first_addon = True
                addon_formatting = formatting_chars
            else:
                addon = (' ' * prefix_width) + '#'
                first_addon = False
                addon_formatting = 0
            if len(addon + description[0]) - addon_formatting + 1 > self.term_width:
                if first_addon:
                    output.append(addon)
                break
            while len(description) > 0:
                if len(addon + description[0]) - addon_formatting + 1 > self.term_width:
                    break
                addon = addon + ' ' + description[0]
                description.pop(0)
            output.append(addon)
        out.write('\n'.join(output) + '\n')

    #--------- per-parameter inp helpers ------------------------------------------

    def __ms_inp(self):
        glb     = self.__globals_()
        value   = glb.get('ms', self._arg_default['ms'])
        default = self._arg_default['ms']
        desc    = self._arg_description.get('ms', '')
        if self.__validate_('ms', value):
            pre, post, fmt = ('\x1B[34m', '\x1B[0m', len('\x1B[34m') + len('\x1B[0m')) \
                if value != default else ('', '', 0)
        else:
            pre, post, fmt = '\x1B[91m', '\x1B[0m', len('\x1B[91m') + len('\x1B[0m')
        self.__do_inp_output(
            '%-23.23s = %s%-23s%s' % ('ms', pre, self.__to_string_(value), post),
            desc, fmt,
        )

    def __ps_inp(self):
        glb     = self.__globals_()
        value   = glb.get('ps', self._arg_default['ps'])
        default = self._arg_default['ps']
        desc    = self._arg_description.get('ps', '')
        if self.__validate_('ps', value):
            pre, post, fmt = ('\x1B[34m', '\x1B[0m', len('\x1B[34m') + len('\x1B[0m')) \
                if value != default else ('', '', 0)
        else:
            pre, post, fmt = '\x1B[91m', '\x1B[0m', len('\x1B[91m') + len('\x1B[0m')
        self.__do_inp_output(
            '%-23.23s = %s%-23s%s' % ('ps', pre, self.__to_string_(value), post),
            desc, fmt,
        )

    def __backend_inp(self):
        glb     = self.__globals_()
        value   = glb.get('backend', self._arg_default['backend'])
        default = self._arg_default['backend']
        desc    = self._arg_description.get('backend', '')
        if self.__validate_('backend', value):
            pre, post, fmt = ('\x1B[34m', '\x1B[0m', len('\x1B[34m') + len('\x1B[0m')) \
                if value != default else ('', '', 0)
        else:
            pre, post, fmt = '\x1B[91m', '\x1B[0m', len('\x1B[91m') + len('\x1B[0m')
        self.__do_inp_output(
            '%-23.23s = %s%-23s%s' % ('backend', pre, self.__to_string_(value), post),
            desc, fmt,
        )

    def __field_inp(self):
        glb     = self.__globals_()
        value   = glb.get('field', self._arg_default['field'])
        default = self._arg_default['field']
        desc    = self._arg_description.get('field', '')
        if self.__validate_('field', value):
            pre, post, fmt = ('\x1B[34m', '\x1B[0m', len('\x1B[34m') + len('\x1B[0m')) \
                if value != default else ('', '', 0)
        else:
            pre, post, fmt = '\x1B[91m', '\x1B[0m', len('\x1B[91m') + len('\x1B[0m')
        self.__do_inp_output(
            '%-23.23s = %s%-23s%s' % ('field', pre, self.__to_string_(value), post),
            desc, fmt,
        )

    def __spw_inp(self):
        glb     = self.__globals_()
        value   = glb.get('spw', self._arg_default['spw'])
        default = self._arg_default['spw']
        desc    = self._arg_description.get('spw', '')
        if self.__validate_('spw', value):
            pre, post, fmt = ('\x1B[34m', '\x1B[0m', len('\x1B[34m') + len('\x1B[0m')) \
                if value != default else ('', '', 0)
        else:
            pre, post, fmt = '\x1B[91m', '\x1B[0m', len('\x1B[91m') + len('\x1B[0m')
        self.__do_inp_output(
            '%-23.23s = %s%-23s%s' % ('spw', pre, self.__to_string_(value), post),
            desc, fmt,
        )

    def __antenna_inp(self):
        glb     = self.__globals_()
        value   = glb.get('antenna', self._arg_default['antenna'])
        default = self._arg_default['antenna']
        desc    = self._arg_description.get('antenna', '')
        if self.__validate_('antenna', value):
            pre, post, fmt = ('\x1B[34m', '\x1B[0m', len('\x1B[34m') + len('\x1B[0m')) \
                if value != default else ('', '', 0)
        else:
            pre, post, fmt = '\x1B[91m', '\x1B[0m', len('\x1B[91m') + len('\x1B[0m')
        self.__do_inp_output(
            '%-23.23s = %s%-23s%s' % ('antenna', pre, self.__to_string_(value), post),
            desc, fmt,
        )

    def __scan_inp(self):
        glb     = self.__globals_()
        value   = glb.get('scan', self._arg_default['scan'])
        default = self._arg_default['scan']
        desc    = self._arg_description.get('scan', '')
        if self.__validate_('scan', value):
            pre, post, fmt = ('\x1B[34m', '\x1B[0m', len('\x1B[34m') + len('\x1B[0m')) \
                if value != default else ('', '', 0)
        else:
            pre, post, fmt = '\x1B[91m', '\x1B[0m', len('\x1B[91m') + len('\x1B[0m')
        self.__do_inp_output(
            '%-23.23s = %s%-23s%s' % ('scan', pre, self.__to_string_(value), post),
            desc, fmt,
        )

    def __timerange_inp(self):
        glb     = self.__globals_()
        value   = glb.get('timerange', self._arg_default['timerange'])
        default = self._arg_default['timerange']
        desc    = self._arg_description.get('timerange', '')
        if self.__validate_('timerange', value):
            pre, post, fmt = ('\x1B[34m', '\x1B[0m', len('\x1B[34m') + len('\x1B[0m')) \
                if value != default else ('', '', 0)
        else:
            pre, post, fmt = '\x1B[91m', '\x1B[0m', len('\x1B[91m') + len('\x1B[0m')
        self.__do_inp_output(
            '%-23.23s = %s%-23s%s' % ('timerange', pre, self.__to_string_(value), post),
            desc, fmt,
        )

    def __uvrange_inp(self):
        glb     = self.__globals_()
        value   = glb.get('uvrange', self._arg_default['uvrange'])
        default = self._arg_default['uvrange']
        desc    = self._arg_description.get('uvrange', '')
        if self.__validate_('uvrange', value):
            pre, post, fmt = ('\x1B[34m', '\x1B[0m', len('\x1B[34m') + len('\x1B[0m')) \
                if value != default else ('', '', 0)
        else:
            pre, post, fmt = '\x1B[91m', '\x1B[0m', len('\x1B[91m') + len('\x1B[0m')
        self.__do_inp_output(
            '%-23.23s = %s%-23s%s' % ('uvrange', pre, self.__to_string_(value), post),
            desc, fmt,
        )

    def __correlation_inp(self):
        glb     = self.__globals_()
        value   = glb.get('correlation', self._arg_default['correlation'])
        default = self._arg_default['correlation']
        desc    = self._arg_description.get('correlation', '')
        if self.__validate_('correlation', value):
            pre, post, fmt = ('\x1B[34m', '\x1B[0m', len('\x1B[34m') + len('\x1B[0m')) \
                if value != default else ('', '', 0)
        else:
            pre, post, fmt = '\x1B[91m', '\x1B[0m', len('\x1B[91m') + len('\x1B[0m')
        self.__do_inp_output(
            '%-23.23s = %s%-23s%s' % ('correlation', pre, self.__to_string_(value), post),
            desc, fmt,
        )

    def __datacolumn_inp(self):
        glb     = self.__globals_()
        value   = glb.get('datacolumn', self._arg_default['datacolumn'])
        default = self._arg_default['datacolumn']
        desc    = self._arg_description.get('datacolumn', '')
        if self.__validate_('datacolumn', value):
            pre, post, fmt = ('\x1B[34m', '\x1B[0m', len('\x1B[34m') + len('\x1B[0m')) \
                if value != default else ('', '', 0)
        else:
            pre, post, fmt = '\x1B[91m', '\x1B[0m', len('\x1B[91m') + len('\x1B[0m')
        self.__do_inp_output(
            '%-23.23s = %s%-23s%s' % ('datacolumn', pre, self.__to_string_(value), post),
            desc, fmt,
        )

    def __layout_inp(self):
        glb     = self.__globals_()
        value   = glb.get('layout', self._arg_default['layout'])
        default = self._arg_default['layout']
        desc    = self._arg_description.get('layout', '')
        if self.__validate_('layout', value):
            pre, post, fmt = ('\x1B[34m', '\x1B[0m', len('\x1B[34m') + len('\x1B[0m')) \
                if value != default else ('', '', 0)
        else:
            pre, post, fmt = '\x1B[91m', '\x1B[0m', len('\x1B[91m') + len('\x1B[0m')
        self.__do_inp_output(
            '%-23.23s = %s%-23s%s' % ('layout', pre, self.__to_string_(value), post),
            desc, fmt,
        )

    def __preset_inp(self):
        glb     = self.__globals_()
        value   = glb.get('preset', self._arg_default['preset'])
        default = self._arg_default['preset']
        desc    = self._arg_description.get('preset', '')
        if self.__validate_('preset', value):
            pre, post, fmt = ('\x1B[34m', '\x1B[0m', len('\x1B[34m') + len('\x1B[0m')) \
                if value != default else ('', '', 0)
        else:
            pre, post, fmt = '\x1B[91m', '\x1B[0m', len('\x1B[91m') + len('\x1B[0m')
        self.__do_inp_output(
            '%-23.23s = %s%-23s%s' % ('preset', pre, self.__to_string_(value), post),
            desc, fmt,
        )

    def __raster_y_inp(self):
        glb     = self.__globals_()
        value   = glb.get('raster_y', self._arg_default['raster_y'])
        default = self._arg_default['raster_y']
        desc    = self._arg_description.get('raster_y', '')
        if self.__validate_('raster_y', value):
            pre, post, fmt = ('\x1B[34m', '\x1B[0m', len('\x1B[34m') + len('\x1B[0m')) \
                if value != default else ('', '', 0)
        else:
            pre, post, fmt = '\x1B[91m', '\x1B[0m', len('\x1B[91m') + len('\x1B[0m')
        self.__do_inp_output(
            '%-23.23s = %s%-23s%s' % ('raster_y', pre, self.__to_string_(value), post),
            desc, fmt,
        )

    def __raster_x_inp(self):
        glb     = self.__globals_()
        value   = glb.get('raster_x', self._arg_default['raster_x'])
        default = self._arg_default['raster_x']
        desc    = self._arg_description.get('raster_x', '')
        if self.__validate_('raster_x', value):
            pre, post, fmt = ('\x1B[34m', '\x1B[0m', len('\x1B[34m') + len('\x1B[0m')) \
                if value != default else ('', '', 0)
        else:
            pre, post, fmt = '\x1B[91m', '\x1B[0m', len('\x1B[91m') + len('\x1B[0m')
        self.__do_inp_output(
            '%-23.23s = %s%-23s%s' % ('raster_x', pre, self.__to_string_(value), post),
            desc, fmt,
        )

    def __raster_qty_inp(self):
        glb     = self.__globals_()
        value   = glb.get('raster_qty', self._arg_default['raster_qty'])
        default = self._arg_default['raster_qty']
        desc    = self._arg_description.get('raster_qty', '')
        if self.__validate_('raster_qty', value):
            pre, post, fmt = ('\x1B[34m', '\x1B[0m', len('\x1B[34m') + len('\x1B[0m')) \
                if value != default else ('', '', 0)
        else:
            pre, post, fmt = '\x1B[91m', '\x1B[0m', len('\x1B[91m') + len('\x1B[0m')
        self.__do_inp_output(
            '%-23.23s = %s%-23s%s' % ('raster_qty', pre, self.__to_string_(value), post),
            desc, fmt,
        )

    def __scatter_x_inp(self):
        glb     = self.__globals_()
        value   = glb.get('scatter_x', self._arg_default['scatter_x'])
        default = self._arg_default['scatter_x']
        desc    = self._arg_description.get('scatter_x', '')
        if self.__validate_('scatter_x', value):
            pre, post, fmt = ('\x1B[34m', '\x1B[0m', len('\x1B[34m') + len('\x1B[0m')) \
                if value != default else ('', '', 0)
        else:
            pre, post, fmt = '\x1B[91m', '\x1B[0m', len('\x1B[91m') + len('\x1B[0m')
        self.__do_inp_output(
            '%-23.23s = %s%-23s%s' % ('scatter_x', pre, self.__to_string_(value), post),
            desc, fmt,
        )

    def __scatter_y_inp(self):
        glb     = self.__globals_()
        value   = glb.get('scatter_y', self._arg_default['scatter_y'])
        default = self._arg_default['scatter_y']
        desc    = self._arg_description.get('scatter_y', '')
        if self.__validate_('scatter_y', value):
            pre, post, fmt = ('\x1B[34m', '\x1B[0m', len('\x1B[34m') + len('\x1B[0m')) \
                if value != default else ('', '', 0)
        else:
            pre, post, fmt = '\x1B[91m', '\x1B[0m', len('\x1B[91m') + len('\x1B[0m')
        self.__do_inp_output(
            '%-23.23s = %s%-23s%s' % ('scatter_y', pre, self.__to_string_(value), post),
            desc, fmt,
        )

    def __time_range_inp(self):
        glb     = self.__globals_()
        value   = glb.get('time_range', self._arg_default['time_range'])
        default = self._arg_default['time_range']
        desc    = self._arg_description.get('time_range', '')
        if self.__validate_('time_range', value):
            pre, post, fmt = ('\x1B[34m', '\x1B[0m', len('\x1B[34m') + len('\x1B[0m')) \
                if value != default else ('', '', 0)
        else:
            pre, post, fmt = '\x1B[91m', '\x1B[0m', len('\x1B[91m') + len('\x1B[0m')
        self.__do_inp_output(
            '%-23.23s = %s%-23s%s' % ('time_range', pre, self.__to_string_(value), post),
            desc, fmt,
        )

    def __freq_range_inp(self):
        glb     = self.__globals_()
        value   = glb.get('freq_range', self._arg_default['freq_range'])
        default = self._arg_default['freq_range']
        desc    = self._arg_description.get('freq_range', '')
        if self.__validate_('freq_range', value):
            pre, post, fmt = ('\x1B[34m', '\x1B[0m', len('\x1B[34m') + len('\x1B[0m')) \
                if value != default else ('', '', 0)
        else:
            pre, post, fmt = '\x1B[91m', '\x1B[0m', len('\x1B[91m') + len('\x1B[0m')
        self.__do_inp_output(
            '%-23.23s = %s%-23s%s' % ('freq_range', pre, self.__to_string_(value), post),
            desc, fmt,
        )

    def __uvdist_range_inp(self):
        glb     = self.__globals_()
        value   = glb.get('uvdist_range', self._arg_default['uvdist_range'])
        default = self._arg_default['uvdist_range']
        desc    = self._arg_description.get('uvdist_range', '')
        if self.__validate_('uvdist_range', value):
            pre, post, fmt = ('\x1B[34m', '\x1B[0m', len('\x1B[34m') + len('\x1B[0m')) \
                if value != default else ('', '', 0)
        else:
            pre, post, fmt = '\x1B[91m', '\x1B[0m', len('\x1B[91m') + len('\x1B[0m')
        self.__do_inp_output(
            '%-23.23s = %s%-23s%s' % ('uvdist_range', pre, self.__to_string_(value), post),
            desc, fmt,
        )

    def __compact_toolbar_inp(self):
        glb     = self.__globals_()
        value   = glb.get('compact_toolbar', self._arg_default['compact_toolbar'])
        default = self._arg_default['compact_toolbar']
        desc    = self._arg_description.get('compact_toolbar', '')
        if self.__validate_('compact_toolbar', value):
            pre, post, fmt = ('\x1B[34m', '\x1B[0m', len('\x1B[34m') + len('\x1B[0m')) \
                if value != default else ('', '', 0)
        else:
            pre, post, fmt = '\x1B[91m', '\x1B[0m', len('\x1B[91m') + len('\x1B[0m')
        self.__do_inp_output(
            '%-23.23s = %s%-23s%s' % ('compact_toolbar', pre, self.__to_string_(value), post),
            desc, fmt,
        )

    #--------- global default implementation --------------------------------------
    @static_var('state', __sf__('casa_inp_go_state'))
    def set_global_defaults(self):
        self.set_global_defaults.state['last'] = self
        glb = self.__globals_()
        if 'ms' in glb: del glb['ms']
        if 'ps' in glb: del glb['ps']
        if 'backend' in glb: del glb['backend']
        if 'field' in glb: del glb['field']
        if 'spw' in glb: del glb['spw']
        if 'antenna' in glb: del glb['antenna']
        if 'scan' in glb: del glb['scan']
        if 'timerange' in glb: del glb['timerange']
        if 'uvrange' in glb: del glb['uvrange']
        if 'correlation' in glb: del glb['correlation']
        if 'datacolumn' in glb: del glb['datacolumn']
        if 'layout' in glb: del glb['layout']
        if 'preset' in glb: del glb['preset']
        if 'raster_y' in glb: del glb['raster_y']
        if 'raster_x' in glb: del glb['raster_x']
        if 'raster_qty' in glb: del glb['raster_qty']
        if 'scatter_x' in glb: del glb['scatter_x']
        if 'scatter_y' in glb: del glb['scatter_y']
        if 'time_range' in glb: del glb['time_range']
        if 'freq_range' in glb: del glb['freq_range']
        if 'uvdist_range' in glb: del glb['uvdist_range']
        if 'compact_toolbar' in glb: del glb['compact_toolbar']

    #--------- inp function -------------------------------------------------------
    def inp(self):
        print("# visplot -- %s" % self._info_desc_)
        self.term_width, self.term_height = shutil.get_terminal_size(fallback=(80, 24))
        self.__ms_inp()
        self.__ps_inp()
        self.__field_inp()
        self.__spw_inp()
        self.__antenna_inp()
        self.__scan_inp()
        self.__timerange_inp()
        self.__uvrange_inp()
        self.__correlation_inp()
        self.__datacolumn_inp()
        self.__layout_inp()
        self.__preset_inp()
        self.__raster_y_inp()
        self.__raster_x_inp()
        self.__raster_qty_inp()
        self.__scatter_x_inp()
        self.__scatter_y_inp()
        self.__time_range_inp()
        self.__freq_range_inp()
        self.__uvdist_range_inp()
        self.__compact_toolbar_inp()

    #--------- tget function ------------------------------------------------------
    @static_var('state', __sf__('casa_inp_go_state'))
    def tget(self, savefile=None):
        from runpy import run_path
        filename = savefile
        if filename is None:
            filename = "visplot.last" if os.path.isfile("visplot.last") \
                else "visplot.saved"
        if os.path.isfile(filename):
            glob = _find_frame()
            newglob = run_path(filename, init_globals={})
            for i in newglob:
                glob[i] = newglob[i]
            self.tget.state['last'] = self
        else:
            print("could not find last file: %s\nsetting defaults instead..." % filename)
            self.set_global_defaults()

    #--------- tput function ------------------------------------------------------
    def tput(self, outfile=None):
        def noobj(s):
            if s.startswith('<') and s.endswith('>'):
                return "None"
            return s

        _postfile = outfile if outfile is not None else os.path.realpath('visplot.last')
        glb = self.__globals_()
        _invocation_parameters = OrderedDict()
        _invocation_parameters['ms'] = glb.get('ms', self._arg_default['ms'])
        _invocation_parameters['ps'] = glb.get('ps', self._arg_default['ps'])
        _invocation_parameters['backend'] = glb.get('backend', self._arg_default['backend'])
        _invocation_parameters['field'] = glb.get('field', self._arg_default['field'])
        _invocation_parameters['spw'] = glb.get('spw', self._arg_default['spw'])
        _invocation_parameters['antenna'] = glb.get('antenna', self._arg_default['antenna'])
        _invocation_parameters['scan'] = glb.get('scan', self._arg_default['scan'])
        _invocation_parameters['timerange'] = glb.get('timerange', self._arg_default['timerange'])
        _invocation_parameters['uvrange'] = glb.get('uvrange', self._arg_default['uvrange'])
        _invocation_parameters['correlation'] = glb.get('correlation', self._arg_default['correlation'])
        _invocation_parameters['datacolumn'] = glb.get('datacolumn', self._arg_default['datacolumn'])
        _invocation_parameters['layout'] = glb.get('layout', self._arg_default['layout'])
        _invocation_parameters['preset'] = glb.get('preset', self._arg_default['preset'])
        _invocation_parameters['raster_y'] = glb.get('raster_y', self._arg_default['raster_y'])
        _invocation_parameters['raster_x'] = glb.get('raster_x', self._arg_default['raster_x'])
        _invocation_parameters['raster_qty'] = glb.get('raster_qty', self._arg_default['raster_qty'])
        _invocation_parameters['scatter_x'] = glb.get('scatter_x', self._arg_default['scatter_x'])
        _invocation_parameters['scatter_y'] = glb.get('scatter_y', self._arg_default['scatter_y'])
        _invocation_parameters['time_range'] = glb.get('time_range', self._arg_default['time_range'])
        _invocation_parameters['freq_range'] = glb.get('freq_range', self._arg_default['freq_range'])
        _invocation_parameters['uvdist_range'] = glb.get('uvdist_range', self._arg_default['uvdist_range'])
        _invocation_parameters['compact_toolbar'] = glb.get('compact_toolbar', self._arg_default['compact_toolbar'])

        try:
            with open(_postfile, 'w') as _f:
                for _i in _invocation_parameters:
                    _f.write("%-20s = %s\n" % (_i, noobj(repr(_invocation_parameters[_i]))))
                _f.write("#visplot( ")
                count = 0
                for _i in _invocation_parameters:
                    _f.write("%s=%s" % (_i, noobj(repr(_invocation_parameters[_i]))))
                    count += 1
                    if count < len(_invocation_parameters):
                        _f.write(",")
                _f.write(" )\n")
        except Exception:
            return False
        return True

    #--------- __call__ -----------------------------------------------------------
    def __call__(
            self,
            ms = _UNSET,
            ps = _UNSET,
            backend = _UNSET,
            field = _UNSET,
            spw = _UNSET,
            antenna = _UNSET,
            scan = _UNSET,
            timerange = _UNSET,
            uvrange = _UNSET,
            correlation = _UNSET,
            datacolumn = _UNSET,
            layout = _UNSET,
            preset = _UNSET,
            raster_y = _UNSET,
            raster_x = _UNSET,
            raster_qty = _UNSET,
            scatter_x = _UNSET,
            scatter_y = _UNSET,
            time_range = _UNSET,
            freq_range = _UNSET,
            uvdist_range = _UNSET,
            compact_toolbar = _UNSET,
    ):
        def noobj(s):
            if s.startswith('<') and s.endswith('>'):
                return "None"
            return s

        _prefile  = os.path.realpath('visplot.pre')
        _postfile = os.path.realpath('visplot.last')
        task_result = None
        glb = self.__globals_()

        _invocation_parameters = OrderedDict()
        _arguments = [
            ms,
            ps,
            backend,
            field,
            spw,
            antenna,
            scan,
            timerange,
            uvrange,
            correlation,
            datacolumn,
            layout,
            preset,
            raster_y,
            raster_x,
            raster_qty,
            scatter_x,
            scatter_y,
            time_range,
            freq_range,
            uvdist_range,
            compact_toolbar,
        ]

        if any(x is not _UNSET for x in _arguments):
            # Python-style invocation: use supplied values, fall back to
            # global frame then default.  _UNSET (not None) is the sentinel
            # so that explicitly passing None is correctly forwarded.
            _invocation_parameters['ms'] = \
                ms if ms is not _UNSET \
                else glb.get('ms', self._arg_default['ms'])
            _invocation_parameters['ps'] = \
                ps if ps is not _UNSET \
                else glb.get('ps', self._arg_default['ps'])
            _invocation_parameters['backend'] = \
                backend if backend is not _UNSET \
                else glb.get('backend', self._arg_default['backend'])
            _invocation_parameters['field'] = \
                field if field is not _UNSET \
                else glb.get('field', self._arg_default['field'])
            _invocation_parameters['spw'] = \
                spw if spw is not _UNSET \
                else glb.get('spw', self._arg_default['spw'])
            _invocation_parameters['antenna'] = \
                antenna if antenna is not _UNSET \
                else glb.get('antenna', self._arg_default['antenna'])
            _invocation_parameters['scan'] = \
                scan if scan is not _UNSET \
                else glb.get('scan', self._arg_default['scan'])
            _invocation_parameters['timerange'] = \
                timerange if timerange is not _UNSET \
                else glb.get('timerange', self._arg_default['timerange'])
            _invocation_parameters['uvrange'] = \
                uvrange if uvrange is not _UNSET \
                else glb.get('uvrange', self._arg_default['uvrange'])
            _invocation_parameters['correlation'] = \
                correlation if correlation is not _UNSET \
                else glb.get('correlation', self._arg_default['correlation'])
            _invocation_parameters['datacolumn'] = \
                datacolumn if datacolumn is not _UNSET \
                else glb.get('datacolumn', self._arg_default['datacolumn'])
            _invocation_parameters['layout'] = \
                layout if layout is not _UNSET \
                else glb.get('layout', self._arg_default['layout'])
            _invocation_parameters['preset'] = \
                preset if preset is not _UNSET \
                else glb.get('preset', self._arg_default['preset'])
            _invocation_parameters['raster_y'] = \
                raster_y if raster_y is not _UNSET \
                else glb.get('raster_y', self._arg_default['raster_y'])
            _invocation_parameters['raster_x'] = \
                raster_x if raster_x is not _UNSET \
                else glb.get('raster_x', self._arg_default['raster_x'])
            _invocation_parameters['raster_qty'] = \
                raster_qty if raster_qty is not _UNSET \
                else glb.get('raster_qty', self._arg_default['raster_qty'])
            _invocation_parameters['scatter_x'] = \
                scatter_x if scatter_x is not _UNSET \
                else glb.get('scatter_x', self._arg_default['scatter_x'])
            _invocation_parameters['scatter_y'] = \
                scatter_y if scatter_y is not _UNSET \
                else glb.get('scatter_y', self._arg_default['scatter_y'])
            _invocation_parameters['time_range'] = \
                time_range if time_range is not _UNSET \
                else glb.get('time_range', self._arg_default['time_range'])
            _invocation_parameters['freq_range'] = \
                freq_range if freq_range is not _UNSET \
                else glb.get('freq_range', self._arg_default['freq_range'])
            _invocation_parameters['uvdist_range'] = \
                uvdist_range if uvdist_range is not _UNSET \
                else glb.get('uvdist_range', self._arg_default['uvdist_range'])
            _invocation_parameters['compact_toolbar'] = \
                compact_toolbar if compact_toolbar is not _UNSET \
                else glb.get('compact_toolbar', self._arg_default['compact_toolbar'])
        else:
            # inp/go-style invocation: read everything from the global frame
            _invocation_parameters['ms'] = \
                glb.get('ms', self._arg_default['ms'])
            _invocation_parameters['ps'] = \
                glb.get('ps', self._arg_default['ps'])
            _invocation_parameters['backend'] = \
                glb.get('backend', self._arg_default['backend'])
            _invocation_parameters['field'] = \
                glb.get('field', self._arg_default['field'])
            _invocation_parameters['spw'] = \
                glb.get('spw', self._arg_default['spw'])
            _invocation_parameters['antenna'] = \
                glb.get('antenna', self._arg_default['antenna'])
            _invocation_parameters['scan'] = \
                glb.get('scan', self._arg_default['scan'])
            _invocation_parameters['timerange'] = \
                glb.get('timerange', self._arg_default['timerange'])
            _invocation_parameters['uvrange'] = \
                glb.get('uvrange', self._arg_default['uvrange'])
            _invocation_parameters['correlation'] = \
                glb.get('correlation', self._arg_default['correlation'])
            _invocation_parameters['datacolumn'] = \
                glb.get('datacolumn', self._arg_default['datacolumn'])
            _invocation_parameters['layout'] = \
                glb.get('layout', self._arg_default['layout'])
            _invocation_parameters['preset'] = \
                glb.get('preset', self._arg_default['preset'])
            _invocation_parameters['raster_y'] = \
                glb.get('raster_y', self._arg_default['raster_y'])
            _invocation_parameters['raster_x'] = \
                glb.get('raster_x', self._arg_default['raster_x'])
            _invocation_parameters['raster_qty'] = \
                glb.get('raster_qty', self._arg_default['raster_qty'])
            _invocation_parameters['scatter_x'] = \
                glb.get('scatter_x', self._arg_default['scatter_x'])
            _invocation_parameters['scatter_y'] = \
                glb.get('scatter_y', self._arg_default['scatter_y'])
            _invocation_parameters['time_range'] = \
                glb.get('time_range', self._arg_default['time_range'])
            _invocation_parameters['freq_range'] = \
                glb.get('freq_range', self._arg_default['freq_range'])
            _invocation_parameters['uvdist_range'] = \
                glb.get('uvdist_range', self._arg_default['uvdist_range'])
            _invocation_parameters['compact_toolbar'] = \
                glb.get('compact_toolbar', self._arg_default['compact_toolbar'])

        try:
            with open(_prefile, 'w') as _f:
                for _i in _invocation_parameters:
                    _f.write("%-20s = %s\n" % (_i, noobj(repr(_invocation_parameters[_i]))))
                _f.write("#visplot( ")
                count = 0
                for _i in _invocation_parameters:
                    _f.write("%s=%s" % (_i, noobj(repr(_invocation_parameters[_i]))))
                    count += 1
                    if count < len(_invocation_parameters):
                        _f.write(",")
                _f.write(" )\n")
        except Exception:
            pass

        try:
            _logging_state_ = _start_log(
                'visplot',
                [
                    'ms=' + repr(_invocation_parameters['ms']),
                    'ps=' + repr(_invocation_parameters['ps']),
                    'backend=' + repr(_invocation_parameters['backend']),
                    'field=' + repr(_invocation_parameters['field']),
                    'spw=' + repr(_invocation_parameters['spw']),
                    'antenna=' + repr(_invocation_parameters['antenna']),
                    'scan=' + repr(_invocation_parameters['scan']),
                    'timerange=' + repr(_invocation_parameters['timerange']),
                    'uvrange=' + repr(_invocation_parameters['uvrange']),
                    'correlation=' + repr(_invocation_parameters['correlation']),
                    'datacolumn=' + repr(_invocation_parameters['datacolumn']),
                    'layout=' + repr(_invocation_parameters['layout']),
                    'preset=' + repr(_invocation_parameters['preset']),
                    'raster_y=' + repr(_invocation_parameters['raster_y']),
                    'raster_x=' + repr(_invocation_parameters['raster_x']),
                    'raster_qty=' + repr(_invocation_parameters['raster_qty']),
                    'scatter_x=' + repr(_invocation_parameters['scatter_x']),
                    'scatter_y=' + repr(_invocation_parameters['scatter_y']),
                    'time_range=' + repr(_invocation_parameters['time_range']),
                    'freq_range=' + repr(_invocation_parameters['freq_range']),
                    'uvdist_range=' + repr(_invocation_parameters['uvdist_range']),
                    'compact_toolbar=' + repr(_invocation_parameters['compact_toolbar']),
                ],
            )
            task_result = _visplot_t(
                ms = _invocation_parameters['ms'],
                ps = _invocation_parameters['ps'],
                backend = _invocation_parameters['backend'],
                field = _invocation_parameters['field'],
                spw = _invocation_parameters['spw'],
                antenna = _invocation_parameters['antenna'],
                scan = _invocation_parameters['scan'],
                timerange = _invocation_parameters['timerange'],
                uvrange = _invocation_parameters['uvrange'],
                correlation = _invocation_parameters['correlation'],
                datacolumn = _invocation_parameters['datacolumn'],
                layout = _invocation_parameters['layout'],
                preset = _invocation_parameters['preset'],
                raster_y = _invocation_parameters['raster_y'],
                raster_x = _invocation_parameters['raster_x'],
                raster_qty = _invocation_parameters['raster_qty'],
                scatter_x = _invocation_parameters['scatter_x'],
                scatter_y = _invocation_parameters['scatter_y'],
                time_range = _invocation_parameters['time_range'],
                freq_range = _invocation_parameters['freq_range'],
                uvdist_range = _invocation_parameters['uvdist_range'],
                compact_toolbar = _invocation_parameters['compact_toolbar'],
            )
        except Exception as exc:
            _except_log('visplot', exc)
            raise
        finally:
            try:
                os.rename(_prefile, _postfile)
            except Exception:
                pass
            task_result = _end_log(_logging_state_, 'visplot', task_result)

        return task_result

    def notebook(self, *args, **kwargs):
        from .visplot_notebook import visplot_notebook
        return visplot_notebook(*args, **kwargs)


visplot = _visplot()
