########################################################################
#
# Copyright (C) 2026
# Associated Universities, Inc. Washington DC, USA.
#
# This script is free software; you can redistribute it and/or modify it
# under the terms of the GNU Library General Public License as published by
# the Free Software Foundation; either version 2 of the License, or (at your
# option) any later version.
#
# This library is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
# FITNESS FOR A PARTICULAR PURPOSE.  See the GNU Library General Public
# License for more details.
#
# You should have received a copy of the GNU Library General Public License
# along with this library; if not, write to the Free Software Foundation,
# Inc., 675 Massachusetts Ave, Cambridge, MA 02139, USA.
#
# Correspondence concerning AIPS++ should be adressed as follows:
#        Internet email: casa-feedback@nrao.edu.
#        Postal address: AIPS++ Project Office
#                        National Radio Astronomy Observatory
#                        520 Edgemont Road
#                        Charlottesville, VA 22903-2475 USA
#
########################################################################
##################### generated by sync_layers from VisibilityPlotter
from __future__ import absolute_import
from uuid import uuid4
from cubevis import exe
from typing import Optional
from casatasks.private.task_logging import start_log as _start_log
from casatasks.private.task_logging import end_log as _end_log
from casatasks.private.task_logging import except_log as _except_log
from cubevis.toolbox.visplot.visibility_plotter import VisibilityPlotter


# ---------------------------------------------------------------------------
# Parameter validator
# ---------------------------------------------------------------------------
# Checks each user-supplied argument against the type annotation from
# VisibilityPlotter.__init__ and raises ValueError for obviously wrong types.
# The check is intentionally permissive: None is accepted for any Optional[X]
# or X | None parameter; complex/unknown annotation strings pass through
# unchecked.  This catches gross misuse (e.g. passing an int where a str is
# required) before the task is dispatched.

def _validate_params(
        ms,
        ps,
        backend,
        field,
        spw,
        antenna,
        scan,
        timerange,
        uvrange,
        correlation,
        datacolumn,
        layout,
        preset,
        raster_y,
        raster_x,
        raster_qty,
        scatter_x,
        scatter_y,
        time_range,
        freq_range,
        uvdist_range,
        compact_toolbar,
):
    import re as _re

    _type_map = {
        'ms': 'Optional[str]',
        'ps': 'Optional[str]',
        'backend': 'str',
        'field': 'str',
        'spw': 'str',
        'antenna': 'str',
        'scan': 'str',
        'timerange': 'str',
        'uvrange': 'str',
        'correlation': 'str',
        'datacolumn': 'str',
        'layout': 'str',
        'preset': 'Optional[str]',
        'raster_y': 'Optional[str]',
        'raster_x': 'Optional[str]',
        'raster_qty': 'Optional[str]',
        'scatter_x': 'Optional[str]',
        'scatter_y': 'Optional[str]',
        'time_range': 'tuple[float, float] | list[float] | None',
        'freq_range': 'tuple[float, float] | list[float] | None',
        'uvdist_range': 'tuple[float, float] | list[float] | None',
        'compact_toolbar': 'bool',
    }

    _simple = {
        'str': str, 'int': int, 'float': float,
        'bool': bool, 'tuple': tuple, 'list': list,
    }

    def _check(name, value, ann):
        if not ann:
            return
        # Normalise Optional[X] and X | None to (nullable=True, inner=X)
        nullable = False
        m = _re.match(r'Optional\[(.+)\]', ann)
        if m:
            nullable = True
            ann = m.group(1)
        elif '|' in ann:
            parts = [p.strip() for p in ann.split('|')]
            if 'None' in parts:
                nullable = True
                parts = [p for p in parts if p != 'None']
            ann = '|'.join(parts)
        if nullable and value is None:
            return
        # Parenthesised override expression, e.g. "(tuple, list)"
        if ann.startswith('(') and ann.endswith(')'):
            py_types = tuple(
                _simple[t.strip()]
                for t in ann[1:-1].split(',')
                if t.strip() in _simple
            )
            if py_types and not isinstance(value, py_types):
                type_names = ' or '.join(t.__name__ for t in py_types)
                raise ValueError(
                    f"'visplot' parameter '{name}': expected {type_names}, "
                    f"got {type(value).__name__} ({value!r})"
                )
            return
        # Union of remaining branches after None-stripping
        if '|' in ann:
            py_types = tuple(
                _simple[_re.match(r'(\w+)', b.strip()).group(1)]
                for b in ann.split('|')
                if _re.match(r'(\w+)', b.strip())
                and _re.match(r'(\w+)', b.strip()).group(1) in _simple
            )
            if py_types and not isinstance(value, py_types):
                type_names = ' or '.join(t.__name__ for t in py_types)
                raise ValueError(
                    f"'visplot' parameter '{name}': expected {type_names}, "
                    f"got {type(value).__name__} ({value!r})"
                )
            return
        # Single type — strip parameterisation, e.g. tuple[float, float] → tuple
        base = _re.match(r'(\w+)', ann)
        if base:
            py_type = _simple.get(base.group(1))
            if py_type is not None and not isinstance(value, py_type):
                raise ValueError(
                    f"'visplot' parameter '{name}': expected {py_type.__name__}, "
                    f"got {type(value).__name__} ({value!r})"
                )
    _check('ms', ms, _type_map['ms'])
    _check('ps', ps, _type_map['ps'])
    _check('backend', backend, _type_map['backend'])
    _check('field', field, _type_map['field'])
    _check('spw', spw, _type_map['spw'])
    _check('antenna', antenna, _type_map['antenna'])
    _check('scan', scan, _type_map['scan'])
    _check('timerange', timerange, _type_map['timerange'])
    _check('uvrange', uvrange, _type_map['uvrange'])
    _check('correlation', correlation, _type_map['correlation'])
    _check('datacolumn', datacolumn, _type_map['datacolumn'])
    _check('layout', layout, _type_map['layout'])
    _check('preset', preset, _type_map['preset'])
    _check('raster_y', raster_y, _type_map['raster_y'])
    _check('raster_x', raster_x, _type_map['raster_x'])
    _check('raster_qty', raster_qty, _type_map['raster_qty'])
    _check('scatter_x', scatter_x, _type_map['scatter_x'])
    _check('scatter_y', scatter_y, _type_map['scatter_y'])
    _check('time_range', time_range, _type_map['time_range'])
    _check('freq_range', freq_range, _type_map['freq_range'])
    _check('uvdist_range', uvdist_range, _type_map['uvdist_range'])
    _check('compact_toolbar', compact_toolbar, _type_map['compact_toolbar'])


def _visplot_t(
        *,
        ms: Optional[str] = None,
        ps: Optional[str] = None,
        backend: str = 'auto',
        field: str = '',
        spw: str = '',
        antenna: str = '',
        scan: str = '',
        timerange: str = '',
        uvrange: str = '',
        correlation: str = '',
        datacolumn: str = 'data',
        layout: str = 'side',
        preset: Optional[str] = None,
        raster_y: Optional[str] = None,
        raster_x: Optional[str] = None,
        raster_qty: Optional[str] = None,
        scatter_x: Optional[str] = None,
        scatter_y: Optional[str] = None,
        time_range: tuple[float, float] | list[float] | None = None,
        freq_range: tuple[float, float] | list[float] | None = None,
        uvdist_range: tuple[float, float] | list[float] | None = None,
        compact_toolbar: bool = True,
):
    _app = VisibilityPlotter(
        # user-supplied arguments
        ms = ms,
        ps = ps,
        backend = backend,
        field = field,
        spw = spw,
        antenna = antenna,
        scan = scan,
        timerange = timerange,
        uvrange = uvrange,
        correlation = correlation,
        datacolumn = datacolumn,
        layout = layout,
        preset = preset,
        raster_y = raster_y,
        raster_x = raster_x,
        raster_qty = raster_qty,
        scatter_x = scatter_x,
        scatter_y = scatter_y,
        time_range = time_range,
        freq_range = freq_range,
        uvdist_range = uvdist_range,
        compact_toolbar = compact_toolbar,
        # layer-supplied arguments
        remote_endpoint = None,
        enable_flagging = True,
    )

    id = uuid4( )
    context = exe.Context( exe.Mode.SYNC )
    bokeh_ui, exec_task = _app( context, id )
    bokeh_ui.show( )
    return context.execute( exec_task, id )

class _visplot:
    r"""
    Combined raster + scatter visibility inspection and flagging tool.

    Parameters
    ----------
    ms : str | None
        Path to an MSv2 measurement set.  Exactly one of ``ms`` or ``ps``
        must be supplied.
    ps : str | None
        Path to an MSv4 / Processing Set Zarr store.
    backend : str
        Reduction backend: ``"auto"``, ``"casa6"``, ``"radps"``,
        ``"remote"``, or ``"null"``.  Default ``"auto"``.
    remote_endpoint : str | None
        Required only when ``backend="remote"``.
    field : str
        Field name or integer index string.  Default: first field.
    spw : str
        Comma-separated SPW indices (``"0,1,2,3"``).  Default: all.
    antenna : str
        MSSelection antenna string.  (Stored; not yet wired in preview.)
    scan : str
        MSSelection scan string.  (Stored; not yet wired.)
    timerange : str
        MSSelection time-range string.  (Stored; not wired.)
    uvrange : str
        UV range string.  (Stored; not wired.)
    correlation : str
        Comma-separated correlation labels (``"XX,YY"``).  Default: all.
    datacolumn : str
        Visibility column: ``"data"``, ``"corrected"``, or ``"model"``.
    layout : str
        Panel layout: ``"one"`` (single panel, raster by default in this
        preview — per-panel kind switching is a later addition),
        ``"side"`` (both panels, side by side), or ``"over"`` (both
        panels, one above the other). Default ``"side"``.
    preset : str | None
        Named preset: ``"vplot"``, ``"radplot"``, ``"waterfall"``, or ``None``.
    raster_y, raster_x : str | None
        Explicit raster Y/X axis, e.g. ``"TIME"``, ``"BASELINE"``,
        ``"CHANNEL"``, ``"CORRELATION"``. Takes precedence over
        ``preset``, which takes precedence over the default
        (Time vs. Channel). Validated against the same options the
        raster axis dropdowns expose in the GUI — an invalid value
        raises ``ValueError`` listing the valid options.
    raster_qty : str | None
        Explicit raster quantity (color axis), e.g. ``"AMPLITUDE"``,
        ``"PHASE"``, ``"REAL"``, ``"IMAGINARY"``, ``"FLAG"``. Same
        precedence and validation as ``raster_y``/``raster_x``.
    scatter_x, scatter_y : str | None
        Explicit scatter X/Y axis, e.g. ``"UVDIST"``, ``"TIME"``,
        ``"FREQUENCY"``, ``"CHANNEL"``, ``"UVDIST_LAMBDA"``, ``"U"``,
        ``"V"`` for X; ``"AMPLITUDE"``, ``"PHASE"``, ``"REAL"``,
        ``"IMAGINARY"``, ``"U"``, ``"V"`` for Y. Same precedence and
        validation. E.g. ``scatter_x="U", scatter_y="V"`` launches
        directly into a U-vs-V UV-coverage scatter plot with no manual
        axis-picker step needed.
    time_range : tuple[float, float] | list[float] | None
        ``(start, end)`` as MJD floats.
    freq_range : tuple[float, float] | list[float] | None
        ``(start, end)`` in Hz.
    uvdist_range : tuple[float, float] | list[float] | None
        ``(min, max)`` in metres.
    compact_toolbar : bool
        Whether each figure's toolbar auto-hides until the mouse is over
        that plot.  Defaults to ``True``.
    """

    _info_group_ = """visualization, information,editing, manipulation"""
    _info_desc_  = """A plotter/interactive flagger for visibility data"""

    def __call__(
            self,
            *,
            ms: Optional[str] = None,
            ps: Optional[str] = None,
            backend: str = 'auto',
            field: str = '',
            spw: str = '',
            antenna: str = '',
            scan: str = '',
            timerange: str = '',
            uvrange: str = '',
            correlation: str = '',
            datacolumn: str = 'data',
            layout: str = 'side',
            preset: Optional[str] = None,
            raster_y: Optional[str] = None,
            raster_x: Optional[str] = None,
            raster_qty: Optional[str] = None,
            scatter_x: Optional[str] = None,
            scatter_y: Optional[str] = None,
            time_range: tuple[float, float] | list[float] | None = None,
            freq_range: tuple[float, float] | list[float] | None = None,
            uvdist_range: tuple[float, float] | list[float] | None = None,
            compact_toolbar: bool = True,
    )  -> None:

        _validate_params(
            ms = ms,
            ps = ps,
            backend = backend,
            field = field,
            spw = spw,
            antenna = antenna,
            scan = scan,
            timerange = timerange,
            uvrange = uvrange,
            correlation = correlation,
            datacolumn = datacolumn,
            layout = layout,
            preset = preset,
            raster_y = raster_y,
            raster_x = raster_x,
            raster_qty = raster_qty,
            scatter_x = scatter_x,
            scatter_y = scatter_y,
            time_range = time_range,
            freq_range = freq_range,
            uvdist_range = uvdist_range,
            compact_toolbar = compact_toolbar,
        )
        _logging_state_ = _start_log(
            'visplot',
            [
                'ms=' + repr(ms),
                'ps=' + repr(ps),
                'backend=' + repr(backend),
                'field=' + repr(field),
                'spw=' + repr(spw),
                'antenna=' + repr(antenna),
                'scan=' + repr(scan),
                'timerange=' + repr(timerange),
                'uvrange=' + repr(uvrange),
                'correlation=' + repr(correlation),
                'datacolumn=' + repr(datacolumn),
                'layout=' + repr(layout),
                'preset=' + repr(preset),
                'raster_y=' + repr(raster_y),
                'raster_x=' + repr(raster_x),
                'raster_qty=' + repr(raster_qty),
                'scatter_x=' + repr(scatter_x),
                'scatter_y=' + repr(scatter_y),
                'time_range=' + repr(time_range),
                'freq_range=' + repr(freq_range),
                'uvdist_range=' + repr(uvdist_range),
                'compact_toolbar=' + repr(compact_toolbar),
            ],
        )
        task_result = None
        try:
            task_result = _visplot_t(
                ms = ms,
                ps = ps,
                backend = backend,
                field = field,
                spw = spw,
                antenna = antenna,
                scan = scan,
                timerange = timerange,
                uvrange = uvrange,
                correlation = correlation,
                datacolumn = datacolumn,
                layout = layout,
                preset = preset,
                raster_y = raster_y,
                raster_x = raster_x,
                raster_qty = raster_qty,
                scatter_x = scatter_x,
                scatter_y = scatter_y,
                time_range = time_range,
                freq_range = freq_range,
                uvdist_range = uvdist_range,
                compact_toolbar = compact_toolbar,
            )
        except Exception as exc:
            _except_log('visplot', exc)
            raise
        finally:
            task_result = _end_log(_logging_state_, 'visplot', task_result)
        return task_result

    def notebook(self, *args, **kwargs):
        from .visplot_notebook import visplot_notebook
        return visplot_notebook(*args, **kwargs)


visplot = _visplot()
