########################################################################
#
# Copyright (C) 2026
# Associated Universities, Inc. Washington DC, USA.
#
# This script is free software; you can redistribute it and/or modify it
# under the terms of the GNU Library General Public License as published by
# the Free Software Foundation; either version 2 of the License, or (at your
# option) any later version.
#
# This library is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
# FITNESS FOR A PARTICULAR PURPOSE.  See the GNU Library General Public
# License for more details.
#
# You should have received a copy of the GNU Library General Public License
# along with this library; if not, write to the Free Software Foundation,
# Inc., 675 Massachusetts Ave, Cambridge, MA 02139, USA.
#
# Correspondence concerning AIPS++ should be adressed as follows:
#        Internet email: casa-feedback@nrao.edu.
#        Postal address: AIPS++ Project Office
#                        National Radio Astronomy Observatory
#                        520 Edgemont Road
#                        Charlottesville, VA 22903-2475 USA
#
########################################################################
##################### generated by sync_layers from VisibilityPlotter
from __future__ import absolute_import
from uuid import uuid4
from cubevis import exe
from typing import Optional

from cubevis.toolbox.visplot.visibility_plotter import VisibilityPlotter


# ---------------------------------------------------------------------------
# Parameter validator
# ---------------------------------------------------------------------------
# Checks each user-supplied argument against the type annotation from
# VisibilityPlotter.__init__ and raises ValueError for obviously wrong types.
# The check is intentionally permissive: None is accepted for any Optional[X]
# or X | None parameter; complex/unknown annotation strings pass through
# unchecked.  This catches gross misuse (e.g. passing an int where a str is
# required) before the task is dispatched.

def _validate_params(
        ms,
        ps,
        backend,
        kernel_name,
        field,
        spw,
        antenna,
        scan,
        timerange,
        uvrange,
        correlation,
        datacolumn,
        averaging,
        detrend,
        stat_time_window,
        stat_chan_window,
        layout,
        kind,
        preset,
        raster_y,
        raster_x,
        raster_qty,
        scatter_x,
        scatter_y,
        time_range,
        freq_range,
        uvdist_range,
        compact_toolbar,
        plot_width,
        plot_height,
        theme,
        raster_cmap,
        scatter_cmap,
        flag_filters,
        flag_preview,
        flag_display,
        flag_color,
        flag_show_flagged,
        flag_flagged_color,
        frame_cache_mb,
):
    import re as _re

    _type_map = {
        'ms': 'Optional[str]',
        'ps': 'Optional[str]',
        'backend': 'str',
        'kernel_name': 'Optional[str]',
        'field': 'str',
        'spw': 'str',
        'antenna': 'str',
        'scan': 'str',
        'timerange': 'str',
        'uvrange': 'str',
        'correlation': 'str',
        'datacolumn': 'str',
        'averaging': 'str',
        'detrend': 'bool',
        'stat_time_window': '',
        'stat_chan_window': '',
        'layout': 'str',
        'kind': 'Optional[str]',
        'preset': 'Optional[str]',
        'raster_y': 'Optional[str]',
        'raster_x': 'Optional[str]',
        'raster_qty': 'Optional[str]',
        'scatter_x': 'Optional[str]',
        'scatter_y': 'Optional[str]',
        'time_range': 'tuple[float, float] | list[float] | None',
        'freq_range': 'tuple[float, float] | list[float] | None',
        'uvdist_range': 'tuple[float, float] | list[float] | None',
        'compact_toolbar': 'bool',
        'plot_width': 'Optional[int]',
        'plot_height': 'Optional[int]',
        'theme': 'str',
        'raster_cmap': 'Optional[str]',
        'scatter_cmap': 'Optional[str]',
        'flag_filters': 'Optional[dict]',
        'flag_preview': 'bool',
        'flag_display': 'str',
        'flag_color': 'str',
        'flag_show_flagged': 'bool',
        'flag_flagged_color': 'str',
        'frame_cache_mb': 'Optional[float]',
    }

    _simple = {
        'str': str, 'int': int, 'float': float,
        'bool': bool, 'tuple': tuple, 'list': list,
    }

    def _check(name, value, ann):
        if not ann:
            return
        # Normalise Optional[X] and X | None to (nullable=True, inner=X)
        nullable = False
        m = _re.match(r'Optional\[(.+)\]', ann)
        if m:
            nullable = True
            ann = m.group(1)
        elif '|' in ann:
            parts = [p.strip() for p in ann.split('|')]
            if 'None' in parts:
                nullable = True
                parts = [p for p in parts if p != 'None']
            ann = '|'.join(parts)
        if nullable and value is None:
            return
        # Parenthesised override expression, e.g. "(tuple, list)"
        if ann.startswith('(') and ann.endswith(')'):
            py_types = tuple(
                _simple[t.strip()]
                for t in ann[1:-1].split(',')
                if t.strip() in _simple
            )
            if py_types and not isinstance(value, py_types):
                type_names = ' or '.join(t.__name__ for t in py_types)
                raise ValueError(
                    f"'visplot' parameter '{name}': expected {type_names}, "
                    f"got {type(value).__name__} ({value!r})"
                )
            return
        # Union of remaining branches after None-stripping
        if '|' in ann:
            py_types = tuple(
                _simple[_re.match(r'(\w+)', b.strip()).group(1)]
                for b in ann.split('|')
                if _re.match(r'(\w+)', b.strip())
                and _re.match(r'(\w+)', b.strip()).group(1) in _simple
            )
            if py_types and not isinstance(value, py_types):
                type_names = ' or '.join(t.__name__ for t in py_types)
                raise ValueError(
                    f"'visplot' parameter '{name}': expected {type_names}, "
                    f"got {type(value).__name__} ({value!r})"
                )
            return
        # Single type — strip parameterisation, e.g. tuple[float, float] → tuple
        base = _re.match(r'(\w+)', ann)
        if base:
            py_type = _simple.get(base.group(1))
            if py_type is not None and not isinstance(value, py_type):
                raise ValueError(
                    f"'visplot' parameter '{name}': expected {py_type.__name__}, "
                    f"got {type(value).__name__} ({value!r})"
                )
    _check('ms', ms, _type_map['ms'])
    _check('ps', ps, _type_map['ps'])
    _check('backend', backend, _type_map['backend'])
    _check('kernel_name', kernel_name, _type_map['kernel_name'])
    _check('field', field, _type_map['field'])
    _check('spw', spw, _type_map['spw'])
    _check('antenna', antenna, _type_map['antenna'])
    _check('scan', scan, _type_map['scan'])
    _check('timerange', timerange, _type_map['timerange'])
    _check('uvrange', uvrange, _type_map['uvrange'])
    _check('correlation', correlation, _type_map['correlation'])
    _check('datacolumn', datacolumn, _type_map['datacolumn'])
    _check('averaging', averaging, _type_map['averaging'])
    _check('detrend', detrend, _type_map['detrend'])
    _check('stat_time_window', stat_time_window, _type_map['stat_time_window'])
    _check('stat_chan_window', stat_chan_window, _type_map['stat_chan_window'])
    _check('layout', layout, _type_map['layout'])
    _check('kind', kind, _type_map['kind'])
    _check('preset', preset, _type_map['preset'])
    _check('raster_y', raster_y, _type_map['raster_y'])
    _check('raster_x', raster_x, _type_map['raster_x'])
    _check('raster_qty', raster_qty, _type_map['raster_qty'])
    _check('scatter_x', scatter_x, _type_map['scatter_x'])
    _check('scatter_y', scatter_y, _type_map['scatter_y'])
    _check('time_range', time_range, _type_map['time_range'])
    _check('freq_range', freq_range, _type_map['freq_range'])
    _check('uvdist_range', uvdist_range, _type_map['uvdist_range'])
    _check('compact_toolbar', compact_toolbar, _type_map['compact_toolbar'])
    _check('plot_width', plot_width, _type_map['plot_width'])
    _check('plot_height', plot_height, _type_map['plot_height'])
    _check('theme', theme, _type_map['theme'])
    _check('raster_cmap', raster_cmap, _type_map['raster_cmap'])
    _check('scatter_cmap', scatter_cmap, _type_map['scatter_cmap'])
    _check('flag_filters', flag_filters, _type_map['flag_filters'])
    _check('flag_preview', flag_preview, _type_map['flag_preview'])
    _check('flag_display', flag_display, _type_map['flag_display'])
    _check('flag_color', flag_color, _type_map['flag_color'])
    _check('flag_show_flagged', flag_show_flagged, _type_map['flag_show_flagged'])
    _check('flag_flagged_color', flag_flagged_color, _type_map['flag_flagged_color'])
    _check('frame_cache_mb', frame_cache_mb, _type_map['frame_cache_mb'])


def _visplot_t(
        *,
        ms: Optional[str] = None,
        ps: Optional[str] = None,
        backend: str = 'auto',
        kernel_name: Optional[str] = None,
        field: str = '',
        spw: str = '',
        antenna: str = '',
        scan: str = '',
        timerange: str = '',
        uvrange: str = '',
        correlation: str = '',
        datacolumn: str = 'data',
        averaging: str = 'vector',
        detrend: bool = True,
        stat_time_window = 'auto',
        stat_chan_window = 'off',
        layout: str = 'side',
        kind: Optional[str] = None,
        preset: Optional[str] = None,
        raster_y: Optional[str] = None,
        raster_x: Optional[str] = None,
        raster_qty: Optional[str] = None,
        scatter_x: Optional[str] = None,
        scatter_y: Optional[str] = None,
        time_range: tuple[float, float] | list[float] | None = None,
        freq_range: tuple[float, float] | list[float] | None = None,
        uvdist_range: tuple[float, float] | list[float] | None = None,
        compact_toolbar: bool = True,
        plot_width: Optional[int] = None,
        plot_height: Optional[int] = None,
        theme: str = 'dark',
        raster_cmap: Optional[str] = None,
        scatter_cmap: Optional[str] = None,
        flag_filters: Optional[dict] = None,
        flag_preview: bool = False,
        flag_display: str = 'hide',
        flag_color: str = '#ff00ff',
        flag_show_flagged: bool = False,
        flag_flagged_color: str = '#7f849c',
        frame_cache_mb: Optional[float] = None,
):
    _app = VisibilityPlotter(
        # user-supplied arguments
        ms = ms,
        ps = ps,
        backend = backend,
        kernel_name = kernel_name,
        field = field,
        spw = spw,
        antenna = antenna,
        scan = scan,
        timerange = timerange,
        uvrange = uvrange,
        correlation = correlation,
        datacolumn = datacolumn,
        averaging = averaging,
        detrend = detrend,
        stat_time_window = stat_time_window,
        stat_chan_window = stat_chan_window,
        layout = layout,
        kind = kind,
        preset = preset,
        raster_y = raster_y,
        raster_x = raster_x,
        raster_qty = raster_qty,
        scatter_x = scatter_x,
        scatter_y = scatter_y,
        time_range = time_range,
        freq_range = freq_range,
        uvdist_range = uvdist_range,
        compact_toolbar = compact_toolbar,
        plot_width = plot_width,
        plot_height = plot_height,
        theme = theme,
        raster_cmap = raster_cmap,
        scatter_cmap = scatter_cmap,
        flag_filters = flag_filters,
        flag_preview = flag_preview,
        flag_display = flag_display,
        flag_color = flag_color,
        flag_show_flagged = flag_show_flagged,
        flag_flagged_color = flag_flagged_color,
        frame_cache_mb = frame_cache_mb,
        # layer-supplied arguments
        remote_endpoint = None,
        enable_flagging = True,
        headless = False,
    )

    id = uuid4( )
    context = exe.Context( exe.Mode.SYNC )
    bokeh_ui, exec_task = _app( context, id )
    bokeh_ui.show( )
    return context.execute( exec_task, id )

class _visplot:
    r"""
    Combined raster + scatter visibility inspection and flagging tool.

    Parameters
    ----------
    ms : str | None
        Path to an MSv2 measurement set.  Exactly one of ``ms`` or ``ps``
        must be supplied.
    ps : str | None
        Path to an MSv4 / Processing Set Zarr store.
    backend : str
        Reduction backend: ``"auto"``, ``"casa6"``, ``"radps"``,
        ``"remote"``, or ``"null"``.  Default ``"auto"``.
    remote_endpoint : str | None
        Required only when ``backend="remote"``.
    kernel_name : str | None
        Kernelspec name (``jupyter kernelspec list``) to run the
        MSv2/MSv4 access and Datashader rendering on, via
        ``cubevis.remote``.  Required when ``backend="remote"``; with
        ``backend="auto"`` (the default) giving it selects the remote
        backend.  ``ms``/``ps`` is then a path on the kernel's host.  The
        same string you'd pass to ``AsyncKernelManager(kernel_name=...)``
        directly — a local kernel (``"python3"``) works for testing the
        remote *path* without an actual cluster.  Construction blocks
        for the whole connect sequence: seconds against a local kernel,
        up to a couple of minutes on first connect to a real
        ``sshpyk``-provisioned cluster kernel.
    field : str
        Field name or integer index string.  Default: first field.
    spw : str
        Comma-separated SPW indices (``"0,1,2,3"``).  Default: all.
    antenna : str
        MSSelection antenna string (comma-separated names or IDs,
        ``!``-prefixed for exclusion -- see ``_parse_antenna_string``'s
        own docstring for the exact supported subset). Wired to
        ``SelectionSpec.antenna_names`` (I-3, 2026-09); Prev/Next in the
        sidebar steps through ``meta.antennas`` in the dataset's own
        order.  ``NAME&NAME`` tokens select exact baselines instead
        (``"DA44&DV19"``, several separated by ``;`` or ``,``), in
        either order; they take precedence over antenna names.  Sets
        what is initially ticked in the sidebar's Antenna and Baseline
        tables.
    scan : str
        MSSelection scan string.  (Stored; not yet wired.)
    timerange : str
        MSSelection time-range string.  (Stored; not wired.)
    uvrange : str
        UV range string.  (Stored; not wired.)
    correlation : str
        Comma-separated correlation labels (``"XX,YY"``).  Default: all.
    datacolumn : str
        Visibility column: ``"data"``, ``"corrected"``, or ``"model"``.
    averaging : str
        How raster cells combine the samples they cover: ``"vector"``
        (default; average the complex visibility, then take Amplitude /
        Phase -- Amplitude drops where samples are incoherent) or
        ``"scalar"`` (Amplitude is the mean of the amplitudes, Phase the
        circular mean).  Initial value for every raster panel; each
        panel's own "Averaging" control (raster gear tab) changes it
        independently afterwards.
    detrend : bool
        For the Phase RMS and Coherence raster quantities: remove a
        linear phase slope (residual delay along frequency, residual
        rate along time) before the statistic is taken (default
        ``True``).  ``False`` measures the data as they are, slope
        included.  Initial value for every raster panel; each panel's
        "Phase slope" control changes it afterwards.
    stat_time_window : str or float
        Time window the Phase RMS / Coherence statistic is taken within:
        ``"auto"`` (default), ``"off"``, ``"scan"``, or a number of
        seconds.  Where Time is a plot axis every integration shows its
        window's value; where it is not, the windows are pooled into
        each cell.  ``"auto"`` is ``"off"`` in the first case and
        ``"scan"`` in the second.  Windows never span a gap between
        scans.  Initial value for every raster panel; each panel's "Time
        window" control changes it afterwards.
    stat_chan_window : str or int
        Channel window for the same statistic: ``"off"`` (default) or a
        number of channels.  Same rules as ``stat_time_window``.
    layout : str
        Panel layout: ``"one"`` (single panel), ``"side"`` (both
        panels, side by side), or ``"over"`` (both panels, one above
        the other). Default ``"side"``. ``"raster"``/``"scatter"`` are
        also accepted as shorthand for ``layout="one", kind="raster"``/
        ``"scatter"`` — see ``kind`` below. Combining the shortcut with
        an explicit, conflicting ``kind=`` raises ``ValueError``.
    kind : str | None
        Which panel kind leads: ``"raster"`` (default when omitted) or
        ``"scatter"``. For ``layout="one"`` this is the single visible
        panel's kind. For ``layout="side"``/``"over"`` both panels are
        always shown (one raster, one scatter, unchanged) — ``kind``
        only decides which one starts in the primary/first screen
        position; the other always takes the complementary kind.
    preset : str | None
        Named preset: ``"vplot"``, ``"radplot"``, ``"waterfall"``,
        ``"zscore"``, ``"phaserms-time"``, ``"phaserms-freq"``,
        ``"phaserms-uvdist"``, ``"phase-waterfall"``, or ``None``.
    raster_y, raster_x : str | None
        Explicit raster Y/X axis, e.g. ``"TIME"``, ``"BASELINE"``,
        ``"CHANNEL"``, ``"CORRELATION"``. Takes precedence over
        ``preset``, which takes precedence over the default
        (Time vs. Channel). Validated against the same options the
        raster axis dropdowns expose in the GUI — an invalid value
        raises ``ValueError`` listing the valid options.
    raster_qty : str | None
        Explicit raster quantity (color axis), e.g. ``"AMPLITUDE"``,
        ``"PHASE"``, ``"REAL"``, ``"IMAGINARY"``, ``"FLAG"``. Same
        precedence and validation as ``raster_y``/``raster_x``.
    scatter_x, scatter_y : str | None
        Explicit scatter X/Y axis, e.g. ``"UVDIST"``, ``"TIME"``,
        ``"FREQUENCY"``, ``"CHANNEL"``, ``"UVDIST_LAMBDA"``, ``"U"``,
        ``"V"`` for X; ``"AMPLITUDE"``, ``"PHASE"``, ``"REAL"``,
        ``"IMAGINARY"``, ``"U"``, ``"V"`` for Y. Same precedence and
        validation. E.g. ``scatter_x="U", scatter_y="V"`` launches
        directly into a U-vs-V UV-coverage scatter plot with no manual
        axis-picker step needed.
    time_range : tuple[float, float] | list[float] | None
        ``(start, end)`` as MJD floats.
    freq_range : tuple[float, float] | list[float] | None
        ``(start, end)`` in Hz.
    uvdist_range : tuple[float, float] | list[float] | None
        ``(min, max)`` in metres.
    compact_toolbar : bool
        Whether each figure's toolbar auto-hides until the mouse is over
        that plot.  Defaults to ``True``.
    flag_filters : dict | None
        Extra flag filters, ``{name: callable | FlagFilter}``; each callable
        is ``func(ds, **params) -> bool mask`` (see ``flag_filters.py``).
        Selectable in the Flagging controls next to the built-in filters.
        Run only with local data; a remote session offers the built-ins.
    flag_preview : bool
        Review each flag proposal (counts, breakdown, highlighted samples)
        before it is added to the pending flags.  Defaults to ``False``.
    flag_display : str
        How pending flags are shown: ``"hide"`` (flagged points disappear,
        the default) or ``"color"`` (drawn in ``flag_color``).
    flag_color : str
        Colour for pending flags when ``flag_display="color"``.
    flag_show_flagged : bool
        Also draw data that are currently flagged (on disk or pending) in
        ``flag_flagged_color``, so an Unflag box can select them.  Off by
        default; toggled in the Flagging controls.
    flag_flagged_color : str
        Colour for flagged data when ``flag_show_flagged`` is on.
    frame_cache_mb : float | None
        Budget (MiB) of the cache of scatter frames -- the decoded samples a
        scatter panel draws, flags and probes.  When a selection's frames do
        not fit, every redraw and flag operation re-reads them from the data
        (an INFO/WARNING line says so).  ``None`` (default): the
        ``CUBEVIS_VISPLOT_FRAME_CACHE_MB`` environment variable if set, else
        a tenth of physical memory, clamped to 256 MiB .. 4 GiB.  Remote
        sessions apply it in the worker, where the frames live.  Example:
        TW Hya with all fields (2 x 31 M samples, ~1.5 GiB per frame) needs
        about 3-4 GiB; on a 24 GB Mac the 2.4 GiB default evicted frames
        and a flag box took 3.6 s instead of 0.5 s.

    Resource lifecycle
    ------------------
    Constructing a ``VisibilityPlotter`` opens the underlying MSv2/MSv4
    backend (``open_ms``/``open_ps``), which holds real OS file
    descriptors (an ``xr.open_datatree()`` handle -- for MSv2 this is
    backed by ``arcae``/casacore table handles across the main table
    *and* every subtable, so a single open can easily account for
    dozens of descriptors).

    Call ``close()`` -- or use the instance as a context manager --
    once you are done with a plotter, especially in scripts or
    interactive sessions that construct many ``VisibilityPlotter``
    instances in a row (each unclosed instance leaks its backend's
    file descriptors for the life of the process)::

        with VisibilityPlotter(ms=path, headless=True) as vp:
            ...  # export, inspect, etc.
        # backend closed here

    In interactive GUI use, ``close()`` is also called automatically
    when the browser session ends for good (see ``_build_comm``'s
    shutdown handler) and, as a last-resort safety net, from
    ``__del__``.  Neither of those is a substitute for an explicit
    ``close()``/``with`` block: session shutdown only fires if the
    browser tab is actually closed, and ``__del__`` timing is not
    guaranteed once Bokeh/CustomJS callbacks create reference cycles
    back to ``self``.
    """
    _info_group_ = """visualization, information,editing, manipulation"""
    _info_desc_  = """A plotter/interactive flagger for visibility data"""

    def __call__(
            self,
            *,
            ms: Optional[str] = None,
            ps: Optional[str] = None,
            backend: str = 'auto',
            kernel_name: Optional[str] = None,
            field: str = '',
            spw: str = '',
            antenna: str = '',
            scan: str = '',
            timerange: str = '',
            uvrange: str = '',
            correlation: str = '',
            datacolumn: str = 'data',
            averaging: str = 'vector',
            detrend: bool = True,
            stat_time_window = 'auto',
            stat_chan_window = 'off',
            layout: str = 'side',
            kind: Optional[str] = None,
            preset: Optional[str] = None,
            raster_y: Optional[str] = None,
            raster_x: Optional[str] = None,
            raster_qty: Optional[str] = None,
            scatter_x: Optional[str] = None,
            scatter_y: Optional[str] = None,
            time_range: tuple[float, float] | list[float] | None = None,
            freq_range: tuple[float, float] | list[float] | None = None,
            uvdist_range: tuple[float, float] | list[float] | None = None,
            compact_toolbar: bool = True,
            plot_width: Optional[int] = None,
            plot_height: Optional[int] = None,
            theme: str = 'dark',
            raster_cmap: Optional[str] = None,
            scatter_cmap: Optional[str] = None,
            flag_filters: Optional[dict] = None,
            flag_preview: bool = False,
            flag_display: str = 'hide',
            flag_color: str = '#ff00ff',
            flag_show_flagged: bool = False,
            flag_flagged_color: str = '#7f849c',
            frame_cache_mb: Optional[float] = None,
    )  -> None:
        """Construct the plotter.

Split into three phases so a headless export can stop after the
first two.  ``headless=True`` resolves configuration and opens the
data, builds only the panels it will actually export, and returns
without any browser chrome -- no ``CommMgr``, no control pipe, no
figure styling, no layout.

See ``_resolve_config``, ``_build_panels`` and ``_build_gui``."""

        from casatasks.private.task_logging import start_log as _start_log
        from casatasks.private.task_logging import end_log as _end_log
        from casatasks.private.task_logging import except_log as _except_log

        _validate_params(
            ms = ms,
            ps = ps,
            backend = backend,
            kernel_name = kernel_name,
            field = field,
            spw = spw,
            antenna = antenna,
            scan = scan,
            timerange = timerange,
            uvrange = uvrange,
            correlation = correlation,
            datacolumn = datacolumn,
            averaging = averaging,
            detrend = detrend,
            stat_time_window = stat_time_window,
            stat_chan_window = stat_chan_window,
            layout = layout,
            kind = kind,
            preset = preset,
            raster_y = raster_y,
            raster_x = raster_x,
            raster_qty = raster_qty,
            scatter_x = scatter_x,
            scatter_y = scatter_y,
            time_range = time_range,
            freq_range = freq_range,
            uvdist_range = uvdist_range,
            compact_toolbar = compact_toolbar,
            plot_width = plot_width,
            plot_height = plot_height,
            theme = theme,
            raster_cmap = raster_cmap,
            scatter_cmap = scatter_cmap,
            flag_filters = flag_filters,
            flag_preview = flag_preview,
            flag_display = flag_display,
            flag_color = flag_color,
            flag_show_flagged = flag_show_flagged,
            flag_flagged_color = flag_flagged_color,
            frame_cache_mb = frame_cache_mb,
        )
        _logging_state_ = _start_log(
            'visplot',
            [
                'ms=' + repr(ms),
                'ps=' + repr(ps),
                'backend=' + repr(backend),
                'kernel_name=' + repr(kernel_name),
                'field=' + repr(field),
                'spw=' + repr(spw),
                'antenna=' + repr(antenna),
                'scan=' + repr(scan),
                'timerange=' + repr(timerange),
                'uvrange=' + repr(uvrange),
                'correlation=' + repr(correlation),
                'datacolumn=' + repr(datacolumn),
                'averaging=' + repr(averaging),
                'detrend=' + repr(detrend),
                'stat_time_window=' + repr(stat_time_window),
                'stat_chan_window=' + repr(stat_chan_window),
                'layout=' + repr(layout),
                'kind=' + repr(kind),
                'preset=' + repr(preset),
                'raster_y=' + repr(raster_y),
                'raster_x=' + repr(raster_x),
                'raster_qty=' + repr(raster_qty),
                'scatter_x=' + repr(scatter_x),
                'scatter_y=' + repr(scatter_y),
                'time_range=' + repr(time_range),
                'freq_range=' + repr(freq_range),
                'uvdist_range=' + repr(uvdist_range),
                'compact_toolbar=' + repr(compact_toolbar),
                'plot_width=' + repr(plot_width),
                'plot_height=' + repr(plot_height),
                'theme=' + repr(theme),
                'raster_cmap=' + repr(raster_cmap),
                'scatter_cmap=' + repr(scatter_cmap),
                'flag_filters=' + repr(flag_filters),
                'flag_preview=' + repr(flag_preview),
                'flag_display=' + repr(flag_display),
                'flag_color=' + repr(flag_color),
                'flag_show_flagged=' + repr(flag_show_flagged),
                'flag_flagged_color=' + repr(flag_flagged_color),
                'frame_cache_mb=' + repr(frame_cache_mb),
            ],
        )
        task_result = None
        try:
            task_result = _visplot_t(
                ms = ms,
                ps = ps,
                backend = backend,
                kernel_name = kernel_name,
                field = field,
                spw = spw,
                antenna = antenna,
                scan = scan,
                timerange = timerange,
                uvrange = uvrange,
                correlation = correlation,
                datacolumn = datacolumn,
                averaging = averaging,
                detrend = detrend,
                stat_time_window = stat_time_window,
                stat_chan_window = stat_chan_window,
                layout = layout,
                kind = kind,
                preset = preset,
                raster_y = raster_y,
                raster_x = raster_x,
                raster_qty = raster_qty,
                scatter_x = scatter_x,
                scatter_y = scatter_y,
                time_range = time_range,
                freq_range = freq_range,
                uvdist_range = uvdist_range,
                compact_toolbar = compact_toolbar,
                plot_width = plot_width,
                plot_height = plot_height,
                theme = theme,
                raster_cmap = raster_cmap,
                scatter_cmap = scatter_cmap,
                flag_filters = flag_filters,
                flag_preview = flag_preview,
                flag_display = flag_display,
                flag_color = flag_color,
                flag_show_flagged = flag_show_flagged,
                flag_flagged_color = flag_flagged_color,
                frame_cache_mb = frame_cache_mb,
            )
        except Exception as exc:
            _except_log('visplot', exc)
            raise
        finally:
            task_result = _end_log(_logging_state_, 'visplot', task_result)
        return task_result

    def notebook(self, *args, **kwargs):
        from .visplot_notebook import visplot_notebook
        return visplot_notebook(*args, **kwargs)


visplot = _visplot()
